# Generated by Django 4.1.3 on 2022-12-09 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="about",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
