# Generated by Django 4.1.3 on 2023-04-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_userprofile_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="website",
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
