# Generated by Django 4.1.3 on 2022-12-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_userprofile_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profession",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
