# Generated by Django 4.1.3 on 2022-12-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_profession"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="linkdin",
            new_name="linkedin",
        ),
    ]
