# Generated by Django 4.1.3 on 2023-03-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessment",
            name="resource",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="submittedassessment",
            name="resource",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="video",
            name="resource",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
