# Generated by Django 4.1.3 on 2023-03-09 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_assessment_resource_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mark",
        ),
    ]
