# Generated by Django 4.1.3 on 2023-03-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_payment_val_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="payment",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
