# Generated by Django 4.1.3 on 2023-03-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_alter_payment_amount_alter_payment_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.CharField(max_length=60),
        ),
    ]
