# Generated by Django 4.1.3 on 2023-04-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_alter_payment_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("about", models.TextField()),
                ("image", models.ImageField(upload_to="about/")),
            ],
        ),
        migrations.CreateModel(
            name="teamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("about", models.TextField()),
                ("image", models.ImageField(upload_to="teamMember/")),
            ],
        ),
    ]
